; ---------------------------------------------------------------------
; LLM64 - shareware intro (free disk only)
;
; The first file on build/llm64-free.d64. Run Disk / LOAD"*",8,1 boots
; it; it shows the LLM64 logo over a cycling Commodore rainbow with a
; five-row text panel under it (raster split at row 20), plays a SID,
; enforces a short nag countdown, and on any key chain-loads
; the real client - which overwrites this program entirely. The registered
; disk does not carry it, and no resident client byte knows it exists.
;
; See docs/11-shareware-intro.md. Deviations from that spec are marked
; DEVIATION and are written up in the doc's implementation notes.
;
; Memory once init has run:
;   $0334-$03FF  chain-load stub (copied there at exit; cassette buffer)
;   $0400-$07E7  bitmap screen RAM (one color byte per cell; the bar rows
;                are what the rainbow animation rewrites)
;   $0801-<$0C00 this program
;   $0C00-$0FE7  text screen; only rows 20-24 ($0F20+) are ever displayed
;   $2000-$3F3F  multicolor bitmap (the drawn LLM64 logo)
;   $4000-$72BD  the loaded data blob, source of every copy above
;   $B000-$BF95  the relocated tune
;   $DB20-$DBE7  color RAM for the text panel rows only
;
; The logo uses %01 pixels exclusively, so every lit cell takes its color
; from the upper nibble of one screen-RAM byte and color RAM is never read
; above the panel - which is why the blob carries no color RAM, and why
; cycling the rainbow is six 40-byte fills. See tools/make_intro_assets.py.
; ---------------------------------------------------------------------

.setcpu "6502"

; Generated by tools/make_intro_assets.py: SID_INIT, SID_PLAY, SID_SONG,
; SID_SIZE, SID_LOAD, PIC_BG.
.include "intro_gen.inc"

; Linker-defined: the stub ships at __STUBCODE_LOAD__ inside this PRG but
; every label in it is assembled for __STUBCODE_RUN__ ($0334).
.import __STUBCODE_LOAD__, __STUBCODE_RUN__, __STUBCODE_SIZE__

NAG_SECONDS = 10        ; the user may prefer 5; this is the only knob
; The KERNAL's 60Hz CIA tick is off while the intro runs (the raster IRQ
; drives everything), so seconds are counted in frames: PAL 50, and on an
; NTSC machine the countdown runs ~20% short. Harmless for a nag.
FRAMES_PER_SEC = 50

; KERNAL
CHROUT = $FFD2
GETIN  = $FFE4
SETLFS = $FFBA
SETNAM = $FFBD
KLOAD  = $FFD5
IRQDFLT = $EA31         ; jiffy clock + keyboard scan, then $EA81
IRQEXIT = $EA81         ; pull A/X/Y, RTI

; Where the blob's parts sit once loaded (contract with make_intro_assets.py)
BLOB_BITMAP = $4000
BLOB_SCREEN = $5F40
BLOB_TUNE   = $6328

BAR_FRAMES  = 6         ; frames between rainbow steps (~8 steps/sec PAL)

BITMAP  = $2000         ; VIC bank 0, $D018 = $18
SCREEN  = $0400
COLRAM  = $D800
TEXTSCR = $0C00         ; $D018 = $36
TEXTROW = TEXTSCR + 20 * 40     ; $0F20: first displayed text row
TEXTCOL = COLRAM + 20 * 40      ; $DB20
PROMPTROW = TEXTROW + 4 * 40

; Raster split. The visible area starts at line $33; text row 20 begins at
; $33 + 20*8 = $D3, so IRQ B must land on the line before it.
LINE_A = $2D            ; above the display: switch to bitmap
LINE_B = $D2            ; switch to text for the bottom five rows

; memcpy's parameter block: six contiguous zero-page bytes so do_copies
; can pour a table row straight into it. $F7-$FA are the RS-232 buffer
; pointers, dead in a program that never opens RS-232. $FB-$FC is inside
; the relocated tune's $FB-$FE window, which is safe only because every
; copy finishes before SID_INIT is ever called.
CPSRC = $F7
CPDST = $F9
CPLEN = $FB

; ---------------------------------------------------------------------
.segment "LOADADDR"
        .word   $0801

.segment "CODE"
; 10 SYS 2061
        .word   basic_end, 10
        .byte   $9E, "2061", 0
basic_end:
        .word   0

; ---------------------------------------------------------------------
; Init
; ---------------------------------------------------------------------
start:
        ; DEVIATION from docs/11 section 3: the spec says never touch $01
        ; and stay at the boot default $37. That is wrong for a $B000
        ; tune - at $37 the BASIC ROM covers $A000-$BFFF, so `jsr
        ; SID_PLAY` would execute ROM, not the relocated tune. $36 banks
        ; BASIC out and leaves KERNAL and I/O in, which is exactly what
        ; the client runs at (HANDOFF, "Banking"). KERNAL LOAD, CHROUT
        ; and the $EA31 IRQ chain all still work; $37 is restored before
        ; chaining so the client starts on a stock machine.
        sei
        lda     #$36
        sta     $01
        cli

        lda     #0
        sta     $D020
        sta     $D021
        lda     #<msg_loading   ; prints in the power-on text color
        ldx     #>msg_loading
        jsr     print

        ; Boot device, exactly as the client's cfg.c does it.
        lda     $BA
        cmp     #4
        bcs     :+
        lda     #8
:       sta     dev

        lda     #name_d_len
        ldx     #<name_d
        ldy     #>name_d
        jsr     load_file

        ; Blank the text screen's colors before the picture goes up. IRQ B
        ; cannot switch $D018 on row 20's own raster line - the VIC fetches
        ; the video matrix at the start of that badline - so it switches on
        ; the line before, and the right-hand ~60% of the picture's LAST
        ; raster line is drawn in text mode from the untouched top of
        ; $0C00. Clearing with the text color set to black makes that leak
        ; black on black. (The KERNAL's clear fills color RAM from $0286.)
        lda     #0
        sta     $0286
        lda     #147
        jsr     CHROUT

        jsr     do_copies
        jsr     draw_text
        jsr     color_text

        ; The KERNAL cursor blinks into $0400, which is now the picture's
        ; color data. $CC != 0 turns the blink off for good; any cell it
        ; already reversed was overwritten by the screen copy above.
        lda     #1
        sta     $CC

        lda     #SID_SONG
        ldx     #0
        ldy     #0
        jsr     SID_INIT

        sei
        lda     #$7F
        sta     $DC0D           ; CIA1 IRQs off: the raster drives us now
        lda     $DC0D           ; ack any pending one
        lda     #$FF
        sta     $D019
        lda     #$01
        sta     $D01A           ; raster IRQ on
        lda     #LINE_A
        sta     $D012
        lda     #$1B            ; also clears the raster compare MSB
        sta     $D011
        lda     #<irq_a
        sta     $0314
        lda     #>irq_a
        sta     $0315
        lda     #FRAMES_PER_SEC
        sta     tick
        lda     #BAR_FRAMES
        sta     bar_tick
        ldx     #0
        stx     bar_phase
        lda     #NAG_SECONDS
        sta     secs_left
        sta     secs_shown
        cli
        jsr     draw_secs

; ---------------------------------------------------------------------
; Nag countdown, then wait for a key. GETIN is drained throughout the
; countdown so a held key cannot skip it.
; ---------------------------------------------------------------------
count_loop:
        jsr     GETIN           ; drain and discard
        lda     secs_left
        beq     count_done
        cmp     secs_shown
        beq     count_loop
        sta     secs_shown
        jsr     draw_secs
        jmp     count_loop

count_done:
        ldx     #39
:       lda     text_prompt,x
        jsr     pet2scr
        sta     PROMPTROW,x
        dex
        bpl     :-

key_loop:
        jsr     GETIN
        beq     key_loop

; ---------------------------------------------------------------------
; Chain-load. Music stops here rather than playing through the LOAD: the
; SID tick's cycle cost wrecks cycle-counted IEC transfers and the tune
; warbles (HANDOFF rule 5). A clean cut is the correct behavior.
; ---------------------------------------------------------------------
        sei
        lda     #0
        sta     $D418           ; silence
        sta     $D01A           ; raster IRQ off
        lda     #$FF
        sta     $D019
        lda     #$81
        sta     $DC0D           ; CIA1 timer A IRQ back on
        lda     #<IRQDFLT
        sta     $0314
        lda     #>IRQDFLT
        sta     $0315
        lda     #$1B
        sta     $D011           ; text mode
        lda     #$C8
        sta     $D016           ; multicolor off
        lda     #$15
        sta     $D018           ; screen $0400, uppercase charset
        lda     #$37
        sta     $01             ; a stock machine for the chained client
        lda     #0
        sta     $C6             ; drop the key that dismissed the intro
        lda     #14
        sta     $0286
        lda     #<msg_loading
        ldx     #>msg_loading
        jsr     print
        cli

        ldx     #<__STUBCODE_SIZE__
:       lda     __STUBCODE_LOAD__ - 1,x
        sta     __STUBCODE_RUN__ - 1,x
        dex
        bne     :-
        jmp     __STUBCODE_RUN__

; ---------------------------------------------------------------------
; Raster IRQs. Two handlers, each arming the other.
; ---------------------------------------------------------------------
; A, above the display: bitmap on, play one frame of music, count time.
irq_a:
        lda     #$FF
        sta     $D019
        lda     #$3B
        sta     $D011           ; bitmap mode
        lda     #$D8
        sta     $D016           ; multicolor, 40 columns
        lda     #$18
        sta     $D018           ; screen $0400, bitmap $2000
        lda     #PIC_BG
        sta     $D021
        jsr     SID_PLAY
        dec     bar_tick
        bne     @nobars
        lda     #BAR_FRAMES
        sta     bar_tick
        jsr     bars_step
@nobars:
        dec     tick
        bne     :+
        lda     #FRAMES_PER_SEC
        sta     tick
        lda     secs_left
        beq     :+
        dec     secs_left
:       lda     #LINE_B
        sta     $D012
        lda     #<irq_b
        sta     $0314
        lda     #>irq_b
        sta     $0315
        jmp     IRQDFLT         ; keyboard scan: GETIN depends on it

; B, just above text row 20: text mode for the panel.
irq_b:
        lda     #$FF
        sta     $D019
        lda     #$1B
        sta     $D011
        lda     #$C8
        sta     $D016
        lda     #$36
        sta     $D018           ; screen $0C00, lowercase charset $1800
        lda     #0
        sta     $D021
        lda     #LINE_A
        sta     $D012
        lda     #<irq_a
        sta     $0314
        lda     #>irq_a
        sta     $0315
        jmp     IRQEXIT         ; a bare RTI here would corrupt A/X/Y

; ---------------------------------------------------------------------
; Helpers
; ---------------------------------------------------------------------
; A = name length, X/Y = name pointer. Loads with secondary address 1, so
; the file's own load address is used. This is also what the stub does.
load_file:
        jsr     SETNAM
        lda     #1
        ldx     dev
        ldy     #1
        jsr     SETLFS
        lda     #0
        jsr     KLOAD
        bcs     @failed
        rts
@failed:
        lda     #<msg_err
        ldx     #>msg_err
        jsr     print
:       jmp     :-              ; a bad disk is a bad disk

; A/X = pointer to a zero-terminated PETSCII string.
print:
        sta     CPSRC
        stx     CPSRC+1
        ldy     #0
@next:  lda     (CPSRC),y
        beq     @done
        jsr     CHROUT
        iny
        bne     @next
@done:  rts

; Unpack the blob: one table row (src, dst, length) at a time into
; memcpy's zero-page block. Cheaper than four inlined setups, and the
; table reads as the memory map it is.
do_copies:
        ldy     #0
@row:   ldx     #0
:       lda     copy_tab,y
        sta     CPSRC,x
        iny
        inx
        cpx     #6
        bne     :-
        tya
        pha                     ; memcpy needs Y
        jsr     memcpy
        pla
        tay
        cpy     #copy_tab_len
        bne     @row
        rts

memcpy:
        ldy     #0
        ldx     CPLEN+1
        beq     @tail
@page:  lda     (CPSRC),y
        sta     (CPDST),y
        iny
        bne     @page
        inc     CPSRC+1
        inc     CPDST+1
        dex
        bne     @page
@tail:  ldx     CPLEN
        beq     @done
@byte:  lda     (CPSRC),y
        sta     (CPDST),y
        iny
        dex
        bne     @byte
@done:  rts

; PETSCII (what ca65 -t c64 emits for a string) to screen code. Only the
; ranges the panel text uses: $20-$3F unchanged, $41-$5A lowercase letters
; -> $01-$1A, $C1-$DA uppercase -> $41-$5A.
pet2scr:
        cmp     #$C0
        bcc     @low
        sbc     #$80            ; carry is set
        rts
@low:   cmp     #$40
        bcc     @done
        sec
        sbc     #$40
@done:  rts

; Render the five panel rows into the text screen. Counts up: a
; `dex / bpl` countdown from 199 would exit on the first iteration,
; because 199 already has bit 7 set.
draw_text:
        ldx     #0
:       lda     text_rows,x
        jsr     pet2scr
        sta     TEXTROW,x
        inx
        cpx     #200
        bne     :-
        rts

; One color per panel row, over the picture's own color RAM.
color_text:
        lda     #<TEXTCOL
        sta     CPDST
        lda     #>TEXTCOL
        sta     CPDST+1
        ldx     #0
@row:   lda     row_colors,x
        ldy     #39
:       sta     (CPDST),y
        dey
        bpl     :-
        lda     CPDST
        clc
        adc     #40
        sta     CPDST
        bcc     :+
        inc     CPDST+1
:       inx
        cpx     #5
        bne     @row
        rts

; Roll the rainbow down one row. Each bar row is 40 screen-RAM bytes of a
; single color (the bitmap under them never changes), so a step is six
; 40-byte fills with the palette read at a rotating offset.
; The palette is emitted twice, so X can walk BAR_COUNT entries from any
; starting phase without a wrap test in the loop.
bars_step:
        ldx     bar_phase
        inx
        cpx     #BAR_COUNT
        bcc     :+
        ldx     #0
:       stx     bar_phase
        txa
        clc
        adc     #BAR_COUNT
        sta     bar_end
        lda     #<(SCREEN + BAR_ROW * 40)
        sta     CPDST
        lda     #>(SCREEN + BAR_ROW * 40)
        sta     CPDST+1
@row:   lda     bar_colors,x
        ldy     #39
:       sta     (CPDST),y
        dey
        bpl     :-
        lda     CPDST
        clc
        adc     #40
        sta     CPDST
        bcc     :+
        inc     CPDST+1
:       inx
        cpx     bar_end
        bne     @row
        rts

; Rewrite the countdown's two digit cells in place.
draw_secs:
        ldx     #$20            ; screen code for space
        lda     secs_left
        cmp     #10
        bcc     @ones
        ldx     #$31            ; '1'
        sbc     #10             ; carry is set
@ones:  clc
        adc     #$30
        sta     digit_ones
        stx     digit_tens
        rts

; ---------------------------------------------------------------------
; Chain-load stub. Copied to $0334 and run from there, because the LOAD
; below overwrites this program's image at $0801. Everything it needs -
; the filename, the error text - lives inside it. `dev` is at $02A7,
; which neither the LOAD nor the client's image touches.
; ---------------------------------------------------------------------
.segment "STUBCODE"
stub:
        lda     #stub_name_len
        ldx     #<stub_name
        ldy     #>stub_name
        jsr     SETNAM
        lda     #1
        ldx     dev
        ldy     #1
        jsr     SETLFS
        lda     #0
        jsr     KLOAD
        bcs     @failed
        jmp     $080D           ; cc65's BASIC header is SYS 2061
@failed:
        ldy     #0
@next:  lda     stub_msg,y
        beq     @halt
        jsr     CHROUT
        iny
        bne     @next
@halt:  jmp     @halt
; The client PRG is written to disk by c1541 as "llm64", i.e. the bytes
; $4C $4C $4D $36 $34. DEVIATION from docs/11 section 3, which says
; to spell it uppercase in the source: under `ca65 -t c64` uppercase
; assembles to $CC $CC $CD $36 $34 and the LOAD would fail. Lowercase
; source is what produces the bytes on the disk. Verified with ca65.
stub_name:      .byte   "llm64"
stub_name_len = * - stub_name
stub_msg:       .byte   "load error", 0

; ---------------------------------------------------------------------
.segment "RODATA"
name_d:         .byte   "llm64.d"     ; lowercase: see stub_name above
name_d_len = * - name_d

; Unpacking the blob. Every destination is clear of both this program and
; the blob at $4000, so these are dumb non-overlapping moves.
copy_tab:
        .addr   BLOB_TUNE,   SID_LOAD
        .word   SID_SIZE
        .addr   BLOB_SCREEN, SCREEN
        .word   1000
        .addr   BLOB_BITMAP, BITMAP
        .word   8000
copy_tab_len = * - copy_tab

; Screen-RAM bytes for the rainbow, generated alongside the drawn logo so
; the two can never disagree.
bar_colors:
        BAR_COLOR_TABLE
        BAR_COLOR_TABLE
        .assert * - bar_colors = BAR_COUNT * 2, error, "bar table size mismatch"

msg_loading:    .byte   147, 13, 13, "  loading...", 0  ; 147 = clear
msg_err:        .byte   13, "disk error", 0

; The panel: five rows of exactly 40 columns, PETSCII, converted to
; screen codes at run time. Lowercase source letters render as capitals
; only after pet2scr; uppercase source (LLM64, AI, SID) renders as
; capitals in the lowercase charset. Count every row - the assembler
; will not do it for you, so .assert does.
; Blank rows 1 and 3 are deliberate breathing room, not leftovers: the
; pitch lines that were here made the panel read as clutter under the
; logo. They must still be written - the clear at init only touches the
; KERNAL's own screen at $0400, so $0C00 is uninitialized RAM.
text_rows:
row0:   .byte   "          LLM64  *  shareware           "
        .assert * - row0 = 40, error, "panel row 0 is not 40 columns"
row1:   .byte   "                                        "
        .assert * - row1 = 40, error, "panel row 1 is not 40 columns"
row2:   .byte   "  foxipso.com | patreon.com/c/foxipso   "
        .assert * - row2 = 40, error, "panel row 2 is not 40 columns"
row3:   .byte   "                                        "
        .assert * - row3 = 40, error, "panel row 3 is not 40 columns"
row4:   .byte   "       please wait 10 seconds...        "
        .assert * - row4 = 40, error, "panel row 4 is not 40 columns"
        .assert * - text_rows = 200, error, "panel is not five rows"

; The two digit cells inside row 4, addressed directly by draw_secs.
digit_tens = PROMPTROW + 19
digit_ones = PROMPTROW + 20

text_prompt:
        .byte   " press any key - registered skips this  "
        .assert * - text_prompt = 40, error, "prompt row is not 40 columns"

row_colors:
        .byte   1, 0, 3, 0, 7           ; title white, links cyan, prompt yellow

; ---------------------------------------------------------------------
.segment "VARS"
dev:            .res    1       ; boot device; read by the stub at $0334
tick:           .res    1       ; frames left in the current second
bar_tick:       .res    1       ; frames left before the rainbow steps
bar_phase:      .res    1       ; palette offset of the topmost bar
bar_end:        .res    1       ; bars_step's palette stop index
secs_left:      .res    1
secs_shown:     .res    1       ; what the panel currently displays
