#!/usr/bin/env python3
"""Compose, assemble and package the intro theme as a .sid.

The shareware intro used to carry an HVSC tune, which is somebody else's
copyrighted work; this builds one that is ours instead. The score lives
here as note names, the player lives in c64_client/intro/tune/llm64_theme.s,
and the output is a PSID file loading at $B000 - the same shape as a
sidreloc'd library tune, so make_intro_assets.py can consume it unchanged.

    python3 tools/make_intro_tune.py       # -> intro/assets/llm64_theme.sid
    python3 tools/make_intro_tune.py --play     # ...and audition it in vsid

Needs ca65/ld65 (cc65), which the client already builds with.
"""

import argparse
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TUNE_DIR = REPO / 'c64_client' / 'intro' / 'tune'
OUT_DEFAULT = REPO / 'c64_client' / 'intro' / 'assets' / 'llm64_theme.sid'

LOAD, INIT, PLAY = 0xB000, 0xB000, 0xB003

NAME = 'Attract Mode'
AUTHOR = 'LLM64'
RELEASED = '2026 llm64'

# 4 octaves, C1..B4. The SID frequency register for a note is
#   f_Hz * 16777216 / PAL_CLOCK, PAL_CLOCK = 985248 Hz
PAL_CLOCK = 985248.0
NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
OCTAVES = range(1, 5)
TEMPO = 8               # frames per row: 8 -> ~6 rows/second at 50 Hz

# --- the score --------------------------------------------------------
# One string per row. '.' is a rest, '-' holds the previous note (the
# player retriggers on every row, so a hold is written as the same note
# again only where a retrigger is wanted). Voice 3 rows take a chord:
# a root note name, suffixed 'm' for minor (the arpeggio picks the third).
#
# Sixteen rows of A minor: i - VI - III - VII, the four chords every
# C64 loader tune was built on.

MELODY = ['A3', '.', 'C4', '.', 'E4', '.', 'D4', 'C4',
          'F3', '.', 'A3', '.', 'C4', '.', 'B3', 'G3']
BASS = ['A1', 'A2', 'A1', 'E2', 'F1', 'F2', 'F1', 'C2',
        'C1', 'C2', 'C1', 'G2', 'G1', 'G2', 'G1', 'E2']
CHORDS = ['Am', '.', '.', '.', 'F', '.', '.', '.',
          'C', '.', '.', '.', 'G', '.', '.', '.']


def note_index(name: str) -> int:
    """1-based index into the frequency table; 0 for a rest."""
    if name in ('.', ''):
        return 0
    pitch = name[:-1]
    octave = int(name[-1])
    if pitch not in NOTE_NAMES or octave not in OCTAVES:
        sys.exit(f'bad note {name!r}')
    return (octave - OCTAVES.start) * 12 + NOTE_NAMES.index(pitch) + 1


def freq_table():
    out = []
    for octave in OCTAVES:
        for semitone in range(12):
            # A4 = 440 Hz; A4 sits at octave 4, semitone 9
            steps = (octave - 4) * 12 + (semitone - 9)
            hz = 440.0 * (2 ** (steps / 12.0))
            out.append(min(0xFFFF, round(hz * 16777216 / PAL_CLOCK)))
    return out


def chord_byte(name: str) -> int:
    if name in ('.', ''):
        return 0
    minor = name.endswith('m')
    root = name[:-1] if minor else name
    # Chord roots are written without an octave; voice 3 sits in octave 3
    idx = note_index(root + '3')
    return idx | (0 if minor else 0x80)


def emit_song_inc(path: Path):
    freqs = freq_table()
    lines = ['; Generated by tools/make_intro_tune.py - do not edit.',
             f'TEMPO = {TEMPO}', '']
    for label, sel in (('freq_lo', lambda f: f & 0xFF),
                       ('freq_hi', lambda f: f >> 8)):
        lines.append(f'{label}:')
        for i in range(0, len(freqs), 12):
            row = ', '.join(f'${sel(f):02x}' for f in freqs[i:i + 12])
            lines.append(f'        .byte {row}')
        lines.append('')
    for label, rows, conv in (('trk1', MELODY, note_index),
                              ('trk2', BASS, note_index),
                              ('trk3', CHORDS, chord_byte)):
        vals = ', '.join(f'${conv(r):02x}' for r in rows)
        lines += [f'{label}:', f'        .byte {vals}',
                  '        .byte $ff', '']
    path.write_text('\n'.join(lines))
    return len(freqs)


def assemble(workdir: Path) -> bytes:
    cfg = workdir / 'tune.cfg'
    cfg.write_text(
        'MEMORY {\n'
        '    RAM: start = $B000, size = $1000, file = %O, fill = no;\n'
        '}\n'
        'SEGMENTS {\n'
        '    TUNE: load = RAM, type = rw;\n'
        '}\n')
    obj, bin_ = workdir / 'tune.o', workdir / 'tune.bin'
    subprocess.run(['ca65', '-t', 'c64', '-I', str(TUNE_DIR),
                    str(TUNE_DIR / 'llm64_theme.s'), '-o', str(obj)],
                   check=True)
    subprocess.run(['ld65', '-C', str(cfg), '-o', str(bin_), str(obj)],
                   check=True)
    return bin_.read_bytes()


def psid(payload: bytes) -> bytes:
    """PSID v2NG header. speed = 0: every subtune is VBI-driven, which is
    what the client's 60 Hz tick provides and what sid_scan.py requires."""
    def field(s):
        return s.encode('latin-1')[:31].ljust(32, b'\0')
    flags = (1 << 2) | (1 << 4)          # PAL, 6581
    head = struct.pack('>4sHHHHHHHI', b'PSID', 2, 0x7C, LOAD, INIT, PLAY,
                       1, 1, 0)
    head += field(NAME) + field(AUTHOR) + field(RELEASED)
    # flags, startPage, pageLength, second/third SID address (bytes, not
    # words - a v2 header is exactly $7C)
    head += struct.pack('>HBBBB', flags, 0, 0, 0, 0)
    assert len(head) == 0x7C, len(head)
    return head + payload


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('-o', '--output', type=Path, default=OUT_DEFAULT)
    ap.add_argument('--play', action='store_true',
                    help='audition the result in vsid when it is built')
    args = ap.parse_args()

    n = emit_song_inc(TUNE_DIR / 'song.inc')
    with tempfile.TemporaryDirectory() as tmp:
        payload = assemble(Path(tmp))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(psid(payload))
    print(f'{args.output}: {len(payload)} bytes of tune '
          f'(${LOAD:04x}-${LOAD + len(payload) - 1:04x}), '
          f'{n} notes in the table, {len(MELODY)} rows')
    if len(payload) > 0x1000:
        sys.exit('tune does not fit the 4 KB window')
    if args.play:
        subprocess.run(['vsid', '-console', '+saveres', str(args.output)])


if __name__ == '__main__':
    main()
